services:
  fukuin-api:
    build: .
    container_name: fukuin-api
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./fukuin.db:/app/fukuin.db
      - ./data:/app/data
    ports:
      - "11000:8000"
    networks:
      - rekai_network
    restart: unless-stopped

networks:
  rekai_network:
    external: true
